name: CI

on: 
  pull_request:
  push:
  workflow_dispatch:
    inputs: 
      is_build:
        description: 'Need to Build?'
        required: true
        type: boolean
jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Build Localizer
        run: dotnet build --project FluentLauncher.Infra.Localizer
      
      - name: Run Localizer
        run: dotnet run --project FluentLauncher.Infra.Localizer -- --src "Views" --out "Strings" --languages en-US zh-Hans zh-Hant ru-RU uk-UA
